### ISSUE TITLE
Filename color

### ISSUE THREAD

**Issue by mdczaplicki** [jpdillingham/slack-desktop-dark-theme#2]
Filename is dark text on dark background. Barely visible.

**Comment by jpdillingham** [comment]
This was changed recently; try exiting and restarting to ensure you have the latest stylesheet.

![image](https://user-images.githubusercontent.com/17145758/46778243-815a9680-ccd8-11e8-9c41-bf07ed626891.png)

**Comment by mdczaplicki** [comment]
I did restart and it is still there.
Maybe for *.zip files it is different as it is zip file.
![image](https://user-images.githubusercontent.com/9108586/46794035-4774a900-cd47-11e8-8bbf-f88b6abb8afa.png)

**Comment by jpdillingham** [comment]
Should be fixed as of this morning, take a look and let me know.  I had previously changed the sidebar, not the channel display.

**Comment by jpdillingham** [comment]
Closing as it looks ok to me.

**Comment by mdczaplicki** [comment]
Yeah, is good now. Sorry didn't let you know.

**Comment by matejdro** [comment]
This is happening again for me with Slack 3.3.7 on Windows 10 and repo version https://github.com/jpdillingham/slack-desktop-dark-theme/tree/ad620822617e2fba8ff26ff8268435071c8c87c1
