### ISSUE TITLE
Channel headers are black

### ISSUE THREAD

**Issue by matejdro** [jpdillingham/slack-desktop-dark-theme#3]
Channel headers (such as Slackbot description or "This is your space" or "This is the very beginning of your direct message history") are black on dark background. See attached screenshot:

![image](https://user-images.githubusercontent.com/507922/54259740-13f0b180-4567-11e9-877a-e01453258295.png)

This is with Slack 3.3.7 on Windows 10 and repo version https://github.com/jpdillingham/slack-desktop-dark-theme/tree/ad620822617e2fba8ff26ff8268435071c8c87c1

**Comment by jpdillingham** [comment]
Should be fixed.
