### ISSUE TITLE
Search bar text is black

### ISSUE THREAD

**Issue by matejdro** [jpdillingham/slack-desktop-dark-theme#6]
Search bar text is black on dark background:

![image](https://user-images.githubusercontent.com/507922/54260241-a80f4880-4568-11e9-964d-1ea0c0183f5d.png)

This is with Slack 3.3.7 on Windows 10 and repo version https://github.com/jpdillingham/slack-desktop-dark-theme/tree/ad620822617e2fba8ff26ff8268435071c8c87c1

**Comment by matejdro** [comment]
Same holds for the search screen that opens up when you click on the search bar.

**Comment by jpdillingham** [comment]
Fixed, along with the search dialog
