### ISSUE TITLE
Broken in Slack v4.0.0

### ISSUE THREAD

**Issue by nicholascapo** [jpdillingham/slack-desktop-dark-theme#8]
Slack version 4.0.0 no longer has a `src` directory in `/usr/lib/slack/resources/app.asar.unpacked`, only `dist`.
This change breaks the dark theme.

**Comment by jpdillingham** [comment]
I can confirm this.  The workaround is to unpack `app.asar` (using [Asar7z](http://www.tc4shell.com/en/7zip/asar/), for instance), update the file, and then re-pack it.

I tried it a few days ago but there's a lot that has changed.  While I was fiddling with it Slack auto-updated with a beta on top of 4.0.0 twice, so I decided to stay on 3.4.3 until the dust settles in a week or two.

According to the Slack team official 'dark mode' for the desktop client is imminent, if you can believe that after 4-5 years of getting the runaround about it.

**Comment by jpdillingham** [comment]
I've got things working with 4.x but the modifications to Slack to get it to load the stylesheet are pretty tedious.  I'm working on a console application to automate this, and will update this issue when it's done.

**Comment by nicholascapo** [comment]
https://slackhq.com/dark-mode-for-slack-desktop

**Comment by jpdillingham** [comment]
Little more contrast than I'd prefer but I'm glad I don't have to maintain this anymore!
